working_directory: "/home/glbrc.org/millican/repos/trait-mapper/workflow"
project_directory: "/home/glbrc.org/millican/repos/trait-mapper"
target_database: ["Competitive_Fitness",'Ecosystem_Service',"Plant_Colonization","Stress_Control", "eps_operon", "nitrogen-cycle"]
sample_directory: "/home/glbrc.org/millican/projects/Inter_BRC/samples"
data_directory: "/home/glbrc.org/millican/projects/Inter_BRC/trait-mapper/data"
pgp_map_pickle: "/home/glbrc.org/millican/repos/trait-mapper/reference_database/pgp_database_map.pkl"
reference_directory: "/home/glbrc.org/millican/projects/Inter_BRC/reference_files/database/pgp"
target_database: ["Competitive_Fitness",'Ecosystem_Service',"Plant_Colonization","Stress_Control", "eps_operon", "nitrogen-cycle"]
taxa: ['archaea', 'bacteria', 'plant', 'viral','fungi','protozoa','invertebrate'] 
kmer: ['21','31','51']
lineage_database: "/home/glbrc.org/millican/projects/Inter_BRC/reference_files/lineage/taxonomy_lineage.db"
RQCFilterData: "/home/glbrc.org/millican/ref_db/RQCFilterData"