jobscript: "/home/glbrc.org/millican/.config/snakemake/HTCondor/grid-jobscript.sh"
cluster: "/home/glbrc.org/millican/.config/snakemake/HTCondor/grid-submit.py"
cluster-status: "/home/glbrc.org/millican/.config/snakemake/HTCondor/grid-status.py"
verbose: False
restart-times: 1
max-jobs-per-second: 1000
max-status-checks-per-second: 1000
latency-wait: 60
jobs: 1000
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
conda-frontend: mamba
cluster-cancel: "/home/glbrc.org/millican/.config/snakemake/HTCondor/grid-cancel.py"
